/**
 * Curated film dataset — sourced from IMDb Non-Commercial Datasets
 * (https://datasets.imdbws.com/)
 *
 * Fields follow the schema of title.basics.tsv + title.ratings.tsv.
 * Mood vectors are hand-tagged to enable behavioral-profile matching.
 */

import { IMDbTitle } from '../types';

export const FILM_CATALOG: IMDbTitle[] = [
  {
    tconst:         'tt0335266',
    primaryTitle:   'Lost in Translation',
    startYear:      2003,
    runtimeMinutes: 102,
    genres:         ['Comedy', 'Drama', 'Romance'],
    averageRating:  7.7,
    numVotes:       475_000,
    mood: { intensity: 0.15, darkness: 0.55, complexity: 0.6, sociality: 0.25 },
  },
  {
    tconst:         'tt0109424',
    primaryTitle:   'Chungking Express',
    startYear:      1994,
    runtimeMinutes: 102,
    genres:         ['Comedy', 'Crime', 'Drama'],
    averageRating:  8.0,
    numVotes:       90_000,
    mood: { intensity: 0.55, darkness: 0.45, complexity: 0.65, sociality: 0.4 },
  },
  {
    tconst:         'tt2582802',
    primaryTitle:   'Whiplash',
    startYear:      2014,
    runtimeMinutes: 106,
    genres:         ['Drama', 'Music'],
    averageRating:  8.5,
    numVotes:       950_000,
    mood: { intensity: 0.95, darkness: 0.6, complexity: 0.45, sociality: 0.2 },
  },
  {
    tconst:         'tt0112471',
    primaryTitle:   'Before Sunrise',
    startYear:      1995,
    runtimeMinutes: 101,
    genres:         ['Drama', 'Romance'],
    averageRating:  8.1,
    numVotes:       325_000,
    mood: { intensity: 0.2, darkness: 0.15, complexity: 0.5, sociality: 0.85 },
  },
  {
    tconst:         'tt0166924',
    primaryTitle:   'Mulholland Drive',
    startYear:      2001,
    runtimeMinutes: 147,
    genres:         ['Drama', 'Mystery', 'Thriller'],
    averageRating:  7.9,
    numVotes:       380_000,
    mood: { intensity: 0.6, darkness: 0.85, complexity: 0.95, sociality: 0.15 },
  },
  {
    tconst:         'tt0118694',
    primaryTitle:   'In the Mood for Love',
    startYear:      2000,
    runtimeMinutes: 98,
    genres:         ['Drama', 'Romance'],
    averageRating:  8.1,
    numVotes:       155_000,
    mood: { intensity: 0.15, darkness: 0.5, complexity: 0.7, sociality: 0.35 },
  },
  {
    tconst:         'tt0838221',
    primaryTitle:   'The Darjeeling Limited',
    startYear:      2007,
    runtimeMinutes: 91,
    genres:         ['Adventure', 'Comedy', 'Drama'],
    averageRating:  7.2,
    numVotes:       230_000,
    mood: { intensity: 0.3, darkness: 0.25, complexity: 0.4, sociality: 0.7 },
  },
  {
    tconst:         'tt0758758',
    primaryTitle:   'Into the Wild',
    startYear:      2007,
    runtimeMinutes: 148,
    genres:         ['Adventure', 'Biography', 'Drama'],
    averageRating:  8.1,
    numVotes:       660_000,
    mood: { intensity: 0.5, darkness: 0.45, complexity: 0.55, sociality: 0.05 },
  },
  {
    tconst:         'tt2872718',
    primaryTitle:   'Nightcrawler',
    startYear:      2014,
    runtimeMinutes: 117,
    genres:         ['Crime', 'Drama', 'Thriller'],
    averageRating:  7.8,
    numVotes:       575_000,
    mood: { intensity: 0.85, darkness: 0.9, complexity: 0.55, sociality: 0.1 },
  },
  {
    tconst:         'tt0095765',
    primaryTitle:   'Cinema Paradiso',
    startYear:      1988,
    runtimeMinutes: 155,
    genres:         ['Drama', 'Romance'],
    averageRating:  8.5,
    numVotes:       280_000,
    mood: { intensity: 0.25, darkness: 0.2, complexity: 0.4, sociality: 0.6 },
  },
  {
    tconst:         'tt0079944',
    primaryTitle:   'Stalker',
    startYear:      1979,
    runtimeMinutes: 163,
    genres:         ['Drama', 'Sci-Fi'],
    averageRating:  8.1,
    numVotes:       140_000,
    mood: { intensity: 0.1, darkness: 0.7, complexity: 0.95, sociality: 0.2 },
  },
  {
    tconst:         'tt0087884',
    primaryTitle:   'Paris, Texas',
    startYear:      1984,
    runtimeMinutes: 145,
    genres:         ['Drama'],
    averageRating:  8.1,
    numVotes:       120_000,
    mood: { intensity: 0.1, darkness: 0.55, complexity: 0.65, sociality: 0.15 },
  },
  {
    tconst:         'tt0146882',
    primaryTitle:   'High Fidelity',
    startYear:      2000,
    runtimeMinutes: 113,
    genres:         ['Comedy', 'Drama', 'Music'],
    averageRating:  7.5,
    numVotes:       215_000,
    mood: { intensity: 0.35, darkness: 0.3, complexity: 0.4, sociality: 0.65 },
  },
  {
    tconst:         'tt2042568',
    primaryTitle:   'Inside Llewyn Davis',
    startYear:      2013,
    runtimeMinutes: 104,
    genres:         ['Drama', 'Music'],
    averageRating:  7.4,
    numVotes:       225_000,
    mood: { intensity: 0.3, darkness: 0.6, complexity: 0.55, sociality: 0.2 },
  },
  {
    tconst:         'tt0780504',
    primaryTitle:   'Drive',
    startYear:      2011,
    runtimeMinutes: 100,
    genres:         ['Action', 'Drama'],
    averageRating:  7.8,
    numVotes:       720_000,
    mood: { intensity: 0.7, darkness: 0.75, complexity: 0.5, sociality: 0.1 },
  },
];
